name: wagmi_web
description: "Wagmi JS SDK wrapper for Dart Web"
version: 2.0.9
homepage: https://github.com/0xMetaLabs/wagmi_web

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  # Collections and utilities functions and classes related to collections
  collection: ^1.18.0
  
  # The decimal package allows you to deal with decimal numbers without losing precision
  decimal: ^3.0.2

  flutter:
    sdk: flutter

  # Annotations for the freezed code-generator. This package does nothing without freezed too
  freezed_annotation: ^3.0.0

  # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization.
  json_annotation: ^4.6.0

  # Logging lib
  logging: ^1.2.0
  
  web: ^1.1.1

dev_dependencies:
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.7.0

  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

  # Code generation for immutable classes that has a simple syntax/API without compromising on the features
  freezed: ^3.2.3

  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.11.1
  test: ^1.25.2

flutter:
  uses-material-design: true
  assets:
    - assets/
